name: Run Python code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: setup python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: 3.13.1
      
    - name: Run Python script
      run: |
        python savefile.py

    - name: List generate
      run: dir /s

    - name: upload
      uses: actions/upload-artifact@v3
      with: 
        name: output-file
        path: gitAction.txt
